/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners;

import Business.Customer;
import Business.Flight;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.time.format.DateTimeFormatter;
import javax.swing.JPanel;

/**
 *
 * @author ishanibose
 */
public class BoardingPass extends javax.swing.JPanel {

    /**
     * Creates new form BoardingPass
     */
    private JPanel userProcessContainer;
    private Customer customer;

    BoardingPass(JPanel userProcessContainer, Customer customer) {
        initComponents();
        this.customer = customer;
        this.userProcessContainer = userProcessContainer;
        populateValues();
    }

    private void populateValues(){
        
        txtAIrlineName.setText(customer.getAirlineName());
        txtFlightNumber.setText(customer.getFlightNumber());
        txtPassengerName.setText(customer.getUsername());
        txtDate.setText(String.valueOf(customer.getDateOfFlight()));
        txtFrom.setText(customer.getFromLocation());
        txtTo.setText(customer.getToLocation());
        txtTime.setText(customer.getTimeOfFlight().format(DateTimeFormatter.ISO_LOCAL_TIME));
        
        String[] temp = customer.getSeatsBoooked();
        String a= "";
        int length = temp.length;
        for(int i=0; i<length; i++){
            if((temp[i] != null))
            a = a + temp[i] + " ";
        }
        txtSeats.setText(a);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAIrlineName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFlightNumber = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPassengerName = new javax.swing.JLabel();
        txtTo = new javax.swing.JLabel();
        txtFrom = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSeats = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTime = new javax.swing.JLabel();

        jLabel1.setText("Airline Name:");

        txtAIrlineName.setText("Airline Name");

        jLabel3.setText("Your Flight:");

        txtFlightNumber.setText("Your Flight");

        jLabel5.setText("Passenger Name:");

        txtPassengerName.setText("Passenger Name");

        txtTo.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        txtTo.setForeground(new java.awt.Color(0, 153, 51));
        txtTo.setText("To");

        txtFrom.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        txtFrom.setForeground(new java.awt.Color(0, 153, 51));
        txtFrom.setText("From");

        jLabel9.setText("Seat No:");

        txtSeats.setText("Seats");

        jLabel11.setText("Journey Date:");

        txtDate.setText("Date");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/ManageAirliners/hangbandongtai.png"))); // NOI18N

        jButton1.setText("Print Pass");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(389, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 255));
        jLabel4.setText("Ticket Confirmation Details");

        jLabel6.setText("Time :");

        txtTime.setText("Time");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtSeats)
                                .addGap(151, 151, 151)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(txtDate)
                                .addGap(73, 73, 73)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtAIrlineName)
                                        .addGap(234, 234, 234)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFlightNumber))
                                    .addComponent(txtPassengerName)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAIrlineName)
                    .addComponent(jLabel3)
                    .addComponent(txtFlightNumber))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPassengerName))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtSeats)
                    .addComponent(jLabel11)
                    .addComponent(txtDate)
                    .addComponent(jLabel6)
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                PrinterJob job = PrinterJob.getPrinterJob();
                job.setJobName("Print Data");

                job.setPrintable(new Printable(){
                public int print(Graphics pg,PageFormat pf, int pageNum){
                        pf.setOrientation(PageFormat.LANDSCAPE);
                     if(pageNum>0){
                        return Printable.NO_SUCH_PAGE;
                    }

                    Graphics2D g2 = (Graphics2D)pg;
                    g2.translate(pf.getImageableX(), pf.getImageableY());
                    g2.scale(0.24,0.24);

                    userProcessContainer.paint(g2);         
                    return Printable.PAGE_EXISTS;


                }
        });    
            boolean ok = job.printDialog();
            if(ok){
            try{

            job.print();
            }
            catch (PrinterException ex){}
            }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtAIrlineName;
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtFlightNumber;
    private javax.swing.JLabel txtFrom;
    private javax.swing.JLabel txtPassengerName;
    private javax.swing.JLabel txtSeats;
    private javax.swing.JLabel txtTime;
    private javax.swing.JLabel txtTo;
    // End of variables declaration//GEN-END:variables
}
