/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.EcoSystem;
import com.teamdev.jxbrowser.browser.Browser;
import com.teamdev.jxbrowser.engine.Engine;
import com.teamdev.jxbrowser.engine.EngineOptions;
import static com.teamdev.jxbrowser.engine.RenderingMode.HARDWARE_ACCELERATED;
import com.teamdev.jxbrowser.view.swing.BrowserView;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.regex.Pattern;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.WindowConstants;

/**
 *
 * @author Vishakha
 */
public class LoadMaps extends javax.swing.JPanel {

    /**
     * Creates new form LoadMaps
     */
    JPanel container;
    Browser browser;
    BrowserView browserView;
    String location;
    EcoSystem ecoSystem;
    private static final int MIN_ZOOM = 0;
    private static final int MAX_ZOOM = 21;
    private static int zoomValue = 8;

    public LoadMaps(JPanel container,EcoSystem system, String location) {
        initComponents();
        this.container = container;
        this.location = location;
        this.ecoSystem = system;
        
       open_map();
    }

    private void open_map() {
        EngineOptions options
                = EngineOptions.newBuilder(HARDWARE_ACCELERATED).licenseKey("6P83ACG409I01JKYU6UO3NWI53G7VD8PTT8UBCKWRB0F3Z7FDMS0HSOKNDD95S0LOO1I").build();
        Engine engine = Engine.newInstance(options);
        browser = engine.newBrowser();
       
        browserView = BrowserView.newInstance(browser);
       
//        JButton zoomInButton = new JButton("Zoom In");
//        zoomInButton.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                if (zoomValue < MAX_ZOOM) {
//                    browser.mainFrame().ifPresent(frame ->
//                            frame.executeJavaScript("map.setZoom(" +
//                                    ++zoomValue + ")"));
//                }
//            }
//        });
//
//        JButton zoomOutButton = new JButton("Zoom Out");
//        zoomOutButton.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                if (zoomValue > MIN_ZOOM) {
//                    browser.mainFrame().ifPresent(frame ->
//                            frame.executeJavaScript("map.setZoom(" +
//                                    ++zoomValue + ")"));
//                }
//            }
//        });
//       JButton setMarkerButton = new JButton("Set Marker");
//       setMarkerButton.addActionListener(new ActionListener() {
//           public void actionPerformed(ActionEvent e) {
//                browser.mainFrame().ifPresent(frame ->
//                            frame.executeJavaScript("var myLatlng = new google.maps.LatLng(48.4431727,23.0488126);\n" +
//                       "var marker = new google.maps.Marker({\n" +
//                       "    position: myLatlng,\n" +
//                       "    map: map,\n" +
//                       "    title: 'Hello World!'\n" +
//                       "});"));
//           }
//       });
//        JPanel toolBar = new JPanel();
//            toolBar.add(zoomInButton);
//            toolBar.add(zoomOutButton);
//            toolBar.add(setMarkerButton);
//        JFrame frame = new JFrame("Google Maps");
//
//        frame.add(browserView, BorderLayout.CENTER);
//        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
//        //frame.add(toolBar, BorderLayout.SOUTH);
//        frame.add(browserView, BorderLayout.CENTER);
//        frame.setSize(800, 500);
//       frame.setVisible(true);
        displayMap.add(browserView, BorderLayout.CENTER);
        browser.navigation().loadUrl("https://www.google.com/maps/search/?api=1&"+"query="+location);
        System.out.println("browser URl "+ browser.url());
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        displayMap = new javax.swing.JPanel();

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jButton1.setText("Set Location");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(231, 231, 231))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(jPanel1);

        displayMap.setBackground(new java.awt.Color(255, 255, 255));
        displayMap.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(displayMap);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if (browser.url()!= null) {

                System.out.println(browser.url());
                String[] a = browser.url().split("!3d"); 
                String[] b = a[1].split("!4d");
                String postion = a[0].substring(a[0].indexOf("place/")+6, a[0].indexOf("/@"));
                location = postion.replaceAll("[^a-zA-Z0-9]", " ");
               
                System.out.println("position"+location);
              
                System.out.println("Lat" + b[0] + "  " + "Lon" + b[1]);
                double latitude = Double.parseDouble(b[0]);
                double longitude = Double.parseDouble(b[1]);
                container.remove(this);
                Component[] componentArray = container.getComponents();
                if(container.getComponent(componentArray.length - 1) instanceof CustomerSignUp){
                    CustomerSignUp customerSignUp = new CustomerSignUp(container,ecoSystem);
                    customerSignUp.populateLocation(location,longitude,latitude);
                }
               
         }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel displayMap;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
