/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Dealer;

import Business.Dealer.Dealer;
import Business.Dealer.DealerCart;
import userinterface.wholeSaleSupplier.*;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Product.Product;
import Business.Product.ProductDirectory;
import Business.Role.AdminRole;
import Business.Role.SystemAdminRole;
import Business.UserAccount.UserAccount;
import Business.WholeSaleSupplier.WholeSaleSupplier;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arthishravan
 */
public class ManageDealerProductsJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Dealer dealer;
    EcoSystem ecosystem;
    ArrayList<DealerCart> cart;
    /**
     * Creates new form CreateResaurantJPanel
     */
    public ManageDealerProductsJPanel(JPanel upc, Dealer deal, EcoSystem system) {
        this.userProcessContainer = upc;
        this.dealer = deal;
        this.ecosystem = system;
        this.cart = new ArrayList<DealerCart>();
        initComponents();
        
        valueLabel.setText(this.dealer.getName());
        populateSupplierTable();
    }
    
    public void populateSupplierTable(){
    DefaultTableModel model = (DefaultTableModel)tblManageDealerSupplier.getModel();
    model.setRowCount(0);

        for (WholeSaleSupplier sup : this.ecosystem.getWholeSaleSupplierDir().getwholeSaleSupplierList()) {
            Object row[] = new Object[2];
            row[0] = sup.getId();
            row[1] = sup;
            model.addRow(row); 
        }
    }
    
    public void populateSupplierProductsTable(WholeSaleSupplier wss){
        DefaultTableModel model = (DefaultTableModel)tblManageSupProducts.getModel();
        model.setRowCount(0);

        for (Product p : wss.getProductDirectory().getProducts()) {
            Object row[] = new Object[4];
            row[0] = p.getId();
            row[1] = p;
            row[2] = p.getPrice();
            row[3] = p.getQty();
            model.addRow(row); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblManageDealerSupplier = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblManageSupProducts = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDealerCart = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        requestTestJButton = new javax.swing.JButton();
        jTextFieldUnitsCount = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Dealer");

        valueLabel.setText("<value>");

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        tblManageDealerSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Whole sale Dealer Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblManageDealerSupplier);

        jLabel2.setText("Choose a Whole Sale Dealer's inventory");

        jButton1.setText("View Products");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Products");

        tblManageSupProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price per Unit", "No. of Units"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblManageSupProducts);

        jButton3.setText("Add to Cart");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tblDealerCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "# of Units"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblDealerCart);

        jLabel4.setText("My Cart");

        jLabel5.setText("Total: $");

        jButton2.setText("Remove Item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        requestTestJButton.setText("Add to Inventory");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("# of Units to buy*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(requestTestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(backJButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldUnitsCount, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3))
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(97, 97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(valueLabel)))
                .addGap(10, 10, 10)
                .addComponent(backJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButton1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldUnitsCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addGap(34, 34, 34)
                .addComponent(requestTestJButton)
                .addContainerGap(361, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DealerWorkAreaJPanel dwajp = (DealerWorkAreaJPanel) component;
        dwajp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblManageDealerSupplier.getSelectedRow();

        if (selectedRow >= 0){
            WholeSaleSupplier wholeSaleSupplierSelected = (WholeSaleSupplier) tblManageDealerSupplier.getValueAt(selectedRow, 1);
            populateSupplierProductsTable(wholeSaleSupplierSelected);
        } else {
            JOptionPane.showMessageDialog(null,"Please select a Whole Sale Dealer", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int selectedProdRow = tblManageSupProducts.getSelectedRow();
        int selectedSupRow = tblManageDealerSupplier.getSelectedRow();
        
        String qtyText = jTextFieldUnitsCount.getText().trim();
        

        if (selectedProdRow >= 0 && selectedSupRow >=0 && !qtyText.isEmpty()){
            Product selectedProduct = (Product) tblManageSupProducts.getValueAt(selectedProdRow, 1);
            WholeSaleSupplier selectedSupplier = (WholeSaleSupplier) tblManageDealerSupplier.getValueAt(selectedSupRow, 1);
            
            //Check if Cart already has the order - product
            boolean foundCartItem = false;
            DealerCart foundCart = null;
            
            for (DealerCart dc : this.cart) {
                if (dc.getName().equals(selectedProduct.getName())) {
                    foundCartItem = true;
                    foundCart = dc;
                    break;
                }
            }
            // Found logic end.
            
            if (foundCartItem) { //Make sure to create one inventory of products and not add them over and over again.
                foundCart.setQty(foundCart.getQty() + Integer.parseInt(qtyText));
            } else {
                DealerCart cartItem = new DealerCart (selectedProduct.getName(), selectedProduct.getPrice(), Integer.parseInt(qtyText), selectedProduct.getCategory());
                this.cart.add(cartItem);
            }
            
            //Update Supplier's inventory count - Start
            //Find Supplier's product record first
            Product supProduct = selectedSupplier.getProductDirectory().findProduct(selectedProduct.getName());
            supProduct.setQty(supProduct.getQty() - Integer.parseInt(qtyText));
            //Update Supplier's inventory count - end

            populateCartTable();
            populateSupplierProductsTable(selectedSupplier);
        } else {
            JOptionPane.showMessageDialog(null,"Please select a Product and # of units to add to the Cart", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    
    public void populateCartTable() {
        DefaultTableModel model = (DefaultTableModel)tblDealerCart.getModel();
        double totalPrice = 0;

        model.setRowCount(0);
        //int count = 1;
        //Supplier supplier = (Supplier)suppComboBox1.getSelectedItem();
        if (cart != null) {
            for(DealerCart c : cart) {
                Object row[] = new Object[3];
                row[0] = c;
                row[1] = c.getPrice();
                row[2] = c.getQty();
                totalPrice = totalPrice + (c.getPrice() * c.getQty()); //Total Price per cart Item Calc
                model.addRow(row); 
                //count++;
            }       
        }

        jLabel5.setText("Total Price: $" + round(totalPrice,2));
    }
    
    public static double round(double value, int places) {
        if (places < 0) throw new IllegalArgumentException();

        long factor = (long) Math.pow(10, places);
        value = value * factor;
        long tmp = Math.round(value);
        return (double) tmp / factor;
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectedCartRow = tblDealerCart.getSelectedRow();
        int selectedSupRow = tblManageDealerSupplier.getSelectedRow();

        if (selectedCartRow >= 0 && selectedSupRow>=0){
            DealerCart cartItem = (DealerCart) tblDealerCart.getValueAt(selectedCartRow, 0);
            WholeSaleSupplier selectedSupplier = (WholeSaleSupplier) tblManageDealerSupplier.getValueAt(selectedSupRow, 1);

            this.cart.remove(cartItem);
            
            //Update Supplier's inventory count - Start
            //Find Supplier's product record first
            Product supProduct = selectedSupplier.getProductDirectory().findProduct(cartItem.getName());
            supProduct.setQty(supProduct.getQty() + cartItem.getQty());
            //Update Supplier's inventory count - end
            
            populateCartTable();
            populateSupplierProductsTable(selectedSupplier);
        } else {
            JOptionPane.showMessageDialog(null,"Please select an item from Cart to remove", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
        int selectedRow = tblManageDealerSupplier.getSelectedRow();

        if (selectedRow >= 0){
            WholeSaleSupplier supplier = (WholeSaleSupplier) tblManageDealerSupplier.getValueAt(selectedRow, 1);
        } else {
            JOptionPane.showMessageDialog(null,"Please select a Supplier to proceed saving...", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        ProductDirectory dealerPd = this.dealer.getProductDirectory();
        ProductDirectory globalPd = this.ecosystem.getProductDirectory();
        

        //Logic for new Products alone.
        for(DealerCart c : cart) {
            Product p = new Product();
            p.setDealer(this.dealer);
            p.setName(c.getName());
            p.setPrice(round(c.getPrice() + (c.getPrice() * .1), 2)); //Dealers sell at 10% profit
            p.setQty(c.getQty());
            p.setCategory(c.getCategory());
            
            addProductToDirectory(p, dealerPd);
            addProductToDirectory(p, globalPd);
        }

        JOptionPane.showMessageDialog(null, "Added Products to Dealer Inventory successfully !!!");

        //Populate previous screen table and navigate back.
        userProcessContainer.remove(this);
        CardLayout cardlayout = (CardLayout) userProcessContainer.getLayout();

        //        Restore prev screen's state
        Component[] comps = userProcessContainer.getComponents();

        for (Component comp : comps){
            if (comp instanceof DealerWorkAreaJPanel){
                System.out.println(comp);
                DealerWorkAreaJPanel manageP = (DealerWorkAreaJPanel) comp;
                manageP.populateRequestTable();
            }
        }

        cardlayout.previous(userProcessContainer);
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    
    private void addProductToDirectory(Product product, ProductDirectory productDirectory) { //Check if product already exists, if so add the qty alone and if not, create the product itself
        Product foundProduct = null;
        
        for (Product p : productDirectory.getProducts()) {
            if (p.getName().equals(product.getName())) {
                foundProduct = p;
            }
        }
        
        if (foundProduct != null) {
            foundProduct.setQty(foundProduct.getQty() + product.getQty());
        } else {
            productDirectory.getProducts().add(product);
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextFieldUnitsCount;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JTable tblDealerCart;
    private javax.swing.JTable tblManageDealerSupplier;
    private javax.swing.JTable tblManageSupProducts;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
