/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.Product.Product;
import Business.WorkQueue.OrderWorkRequest;
import java.awt.CardLayout;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author madhurimachatterjee
 */
public class CustomerReciept extends javax.swing.JPanel {

    /**
     * Creates new form CustomerReciept
     */
    JPanel userProcessContainer;
    OrderWorkRequest order;
    private DefaultTableModel viewTable;
    private static final Object[] columnNames = {"Product Name","Quantity", "Price","Photo"};
    public CustomerReciept(JPanel userProcessContainer, OrderWorkRequest order) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.order = order;
        txtCustomerName.setText(this.order.getCustomer().getName());
        txtOrderID.setText(Integer.toString(this.order.getOrderId()));
        DateFormat dateFormat = new SimpleDateFormat("dd-mm-yyyy hh:mm:ss");  
        String strDate = dateFormat.format(this.order.getOrderDate());
        txtOrderDate.setText(strDate);
        txtPayment.setText(this.order.getPaymentType());
        if(this.order.getTotalPrice() < 100.0)
        {
            txtDiscount.setText("No");
        }
        else
        {
            txtDiscount.setText("Yes");
        }
        viewTable =  new DefaultTableModel(null,columnNames){
            @Override
            public Class<?> getColumnClass(int column) {
                if (column==3) return Icon.class;
                return Object.class;
            }
        };
        populateTable();
        System.out.println(this.order.getProdDir().getProducts().size());
    }

    public void populateTable()
    {
        viewTable.setRowCount(0);
        for (Product prod : order.getProdDir().getProducts()) {
            Object[] row = new Object[viewTable.getColumnCount()];
            row[0] = prod.getName();
            row[1] = prod.getQty();
            row[2] = prod.getQty() * prod.getPrice();
            String temp = prod.getProductImagePath();
                if(temp != null)
                {
                    ImageIcon ii = new ImageIcon(temp);
                    Image resizedImage = ii.getImage();
                    ii = new ImageIcon(resizedImage.getScaledInstance(170, 170, Image.SCALE_SMOOTH));
                    row[3] = ii;
                }
                else
                {
                    row[3] = "Should have been an image";
                }
            viewTable.addRow(row);
        }
        tblProds.setRowHeight(150);
        tblProds.setModel(viewTable);
        btnPrint.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtOrderDate = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtOrderID = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProds = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtPayment = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Order Confirmation Details");

        txtCustomerName.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtCustomerName.setForeground(new java.awt.Color(0, 51, 204));
        txtCustomerName.setText("Custu");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 204));
        jLabel7.setText("Customer Name:");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 204));
        jLabel8.setText("Order Date:");

        txtOrderDate.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtOrderDate.setForeground(new java.awt.Color(0, 51, 204));
        txtOrderDate.setText("Date");

        btnPrint.setBackground(new java.awt.Color(0, 51, 255));
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setText("Print Reciept");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 204));
        jLabel9.setText("Order ID:");

        txtOrderID.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtOrderID.setForeground(new java.awt.Color(0, 51, 204));
        txtOrderID.setText("Ord");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reciept.jpeg"))); // NOI18N

        tblProds.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        tblProds.setForeground(new java.awt.Color(0, 102, 255));
        tblProds.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Quantity", "Total Price", "Photo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProds.setRowSelectionAllowed(false);
        tblProds.setSelectionBackground(new java.awt.Color(153, 153, 255));
        tblProds.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblProds);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 204));
        jLabel11.setText("15% discount applied:");

        txtDiscount.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtDiscount.setForeground(new java.awt.Color(0, 51, 204));
        txtDiscount.setText("Nah");

        btnBack.setForeground(new java.awt.Color(0, 51, 204));
        btnBack.setText("<<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 204));
        jLabel12.setText("Payment Method:");

        txtPayment.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtPayment.setForeground(new java.awt.Color(0, 51, 204));
        txtPayment.setText("Cash");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOrderDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPayment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOrderID)
                    .addComponent(txtDiscount))
                .addGap(76, 76, 76))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack)
                .addGap(218, 218, 218)
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCustomerName)
                            .addComponent(jLabel9)
                            .addComponent(txtOrderID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtDiscount)
                            .addComponent(jLabel8)
                            .addComponent(txtOrderDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtPayment)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Data");
        job.setPrintable(new Printable(){
        public int print(Graphics pg,PageFormat pf, int pageNum)
        {
            pf.setOrientation(PageFormat.LANDSCAPE);
            if(pageNum>0)
            {
                return Printable.NO_SUCH_PAGE;
            }
            Graphics2D g2 = (Graphics2D)pg;
            g2.translate(pf.getImageableX(), pf.getImageableY());
            g2.scale(0.24,0.24);
            userProcessContainer.paint(g2);         
            return Printable.PAGE_EXISTS;
        }
        });    
        boolean ok = job.printDialog();
        if(ok)
        {
            try
            {
                job.print();
            }
            catch (PrinterException ex){}
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProds;
    private javax.swing.JLabel txtCustomerName;
    private javax.swing.JLabel txtDiscount;
    private javax.swing.JLabel txtOrderDate;
    private javax.swing.JLabel txtOrderID;
    private javax.swing.JLabel txtPayment;
    // End of variables declaration//GEN-END:variables
}
