/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Product.Product;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author madhurimachatterjee
 */
public class ECommerceCustomerCart extends javax.swing.JPanel {

    /**
     * Creates new form ECommerceCustomerCart
     */
    JPanel rightSystemAdminPanel;
    Customer customer;
    private DefaultTableModel viewTable;
    EcoSystem ecosystem;
    private static final Object[] columnNames = {"Product Name","Quantity","Total Price","Photo"};
    public ECommerceCustomerCart(JPanel rightSystemAdminPanel, Customer customer, EcoSystem ecosystem) {
        initComponents();
        this.rightSystemAdminPanel = rightSystemAdminPanel;
        this.customer = customer;
        this.ecosystem = ecosystem;
        lblName.setText(this.customer.getName() + "'s Cart");
        
        viewTable =  new DefaultTableModel(null,columnNames){
            @Override
            public Class<?> getColumnClass(int column) {
                if (column==3) return Icon.class;
                return Object.class;
            }
        };
        populateTable();
        this.customer.getCart().calculateTotalPrice();
        txtTotalPrice.setText(Double.toString((this.customer.getCart().getTotalPrice())));
    }

    public void populateTable()
    {
        if(customer.getCart().getProdDir().getProducts() != null)
        {
            for(Product p : customer.getCart().getProdDir().getProducts())
            {
            
                Object[] row = new Object[viewTable.getColumnCount()];
                row[0] = p;
                row[1] = p.getQty();
                row[2] = p.getQty() * p.getPrice();
                String temp = p.getProductImagePath();
                if(temp != null)
                {
                    ImageIcon ii = new ImageIcon(temp);
                    Image resizedImage = ii.getImage();
                    ii = new ImageIcon(resizedImage.getScaledInstance(170, 170, Image.SCALE_SMOOTH));
                    row[3] = ii;
                }
                else
                {
                    row[3] = "Should have been an image";
                }
                viewTable.addRow(row);
            }
            tblCart.setRowHeight(150);
            tblCart.setModel(viewTable);
        }
        
    }
    
    // Listen for changes in the text
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jSpinnerQty = new javax.swing.JSpinner();
        btnPay = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblName.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Quantity", "Total Price", "Photo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCart);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        jLabel2.setText("Total Price:");

        txtTotalPrice.setEditable(false);
        txtTotalPrice.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N

        btnBack.setText("<< Continue Shopping");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete Product");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update Quantity");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jSpinnerQty.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        btnPay.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnPay.setText("Proceed to Payment");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSpinnerQty, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnDelete)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(jSpinnerQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPay)
                .addContainerGap(128, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        rightSystemAdminPanel.remove(this);
        Component[] componentArray = rightSystemAdminPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ECommerceProductPanel eCommProd = (ECommerceProductPanel) component;
        eCommProd.enableCartBtn();
        CardLayout layout = (CardLayout) rightSystemAdminPanel.getLayout();
        layout.previous(rightSystemAdminPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        // TODO add your handling code here:
        ECommerceCustomerPayment eccp = new ECommerceCustomerPayment(rightSystemAdminPanel, customer, ecosystem);
        rightSystemAdminPanel.add("eCommerceCustomerPayment", eccp);
        CardLayout layout = (CardLayout)this.rightSystemAdminPanel.getLayout();
        layout.next(rightSystemAdminPanel);
        
    }//GEN-LAST:event_btnPayActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCart.getSelectedRow();

        if (selectedRow >= 0) 
        {
            Product product = (Product) tblCart.getValueAt(selectedRow, 0);
            //Product foundProduct = customer.getCart().checkIfProductInCart(product);
            product.setQty((Integer)jSpinnerQty.getValue());
            System.out.println(customer.getCart().getProdDir().getProducts().size());
            JOptionPane.showMessageDialog(null, "Product " + product.getName() + " quantity updated to " + product.getQty());
            viewTable.removeRow(tblCart.getSelectedRow());
            populateTable();
            this.customer.getCart().calculateTotalPrice();
            txtTotalPrice.setText(Double.toString((this.customer.getCart().getTotalPrice())));
        } 
        else 
        {
            JOptionPane.showMessageDialog(null, "Choose a product to update first!");
            return;
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCart.getSelectedRow();

        if (selectedRow >= 0) 
        {
            Product product = (Product) tblCart.getValueAt(selectedRow, 0);
            customer.getCart().deleteProductfromCart(product);
            JOptionPane.showMessageDialog(null, "Product " + product.getName() + " removed from cart successfully!");
            viewTable.removeRow(tblCart.getSelectedRow());
            populateTable();
            this.customer.getCart().calculateTotalPrice();
            txtTotalPrice.setText(Double.toString((this.customer.getCart().getTotalPrice())));
            if(Double.parseDouble(txtTotalPrice.getText()) == 0.0)
            {
                btnPay.setEnabled(false);
            }
        } 
        else 
        {
            JOptionPane.showMessageDialog(null, "Choose a product to update first!");
            return;
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerQty;
    private javax.swing.JLabel lblName;
    private javax.swing.JTable tblCart;
    private javax.swing.JTextField txtTotalPrice;
    // End of variables declaration//GEN-END:variables
}
