/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ManufacturerAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Vishakha
 */
public class ManufacturerAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount userAccount;
    Enterprise enterprise;
    Organization organization;
    public ManufacturerAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount,Organization organization,Enterprise enterprise, EcoSystem ecosystem) {
        //this.set
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.organization = organization;
        manageOrders();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        systemAdminPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        manageOrdersButtonPanel = new javax.swing.JPanel();
        manageOrdersButtonLabel = new javax.swing.JLabel();
        manageMenuButtonPanel = new javax.swing.JPanel();
        manageMenuButtonLabel = new javax.swing.JLabel();
        manageInfoButtonPanel = new javax.swing.JPanel();
        manageInfoButtonLabel = new javax.swing.JLabel();
        placeOrderRequestButtonPanel = new javax.swing.JPanel();
        PlaceOrderButtonLabel = new javax.swing.JLabel();
        rightSystemAdminPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(31, 50, 97));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageOrdersButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageOrdersButtonPanelMousePressed(evt);
            }
        });

        manageOrdersButtonLabel.setForeground(new java.awt.Color(0, 0, 153));
        manageOrdersButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageOrdersButtonLabel.setText("Manage Orders");
        manageOrdersButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageOrdersButtonLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout manageOrdersButtonPanelLayout = new javax.swing.GroupLayout(manageOrdersButtonPanel);
        manageOrdersButtonPanel.setLayout(manageOrdersButtonPanelLayout);
        manageOrdersButtonPanelLayout.setHorizontalGroup(
            manageOrdersButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageOrdersButtonPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(manageOrdersButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        manageOrdersButtonPanelLayout.setVerticalGroup(
            manageOrdersButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageOrdersButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manageOrdersButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(manageOrdersButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, -1));

        manageMenuButtonPanel.setPreferredSize(new java.awt.Dimension(264, 48));
        manageMenuButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageMenuButtonPanelMousePressed(evt);
            }
        });

        manageMenuButtonLabel.setForeground(new java.awt.Color(0, 0, 153));
        manageMenuButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageMenuButtonLabel.setText("Manage Products");
        manageMenuButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageMenuButtonLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout manageMenuButtonPanelLayout = new javax.swing.GroupLayout(manageMenuButtonPanel);
        manageMenuButtonPanel.setLayout(manageMenuButtonPanelLayout);
        manageMenuButtonPanelLayout.setHorizontalGroup(
            manageMenuButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageMenuButtonPanelLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(manageMenuButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        manageMenuButtonPanelLayout.setVerticalGroup(
            manageMenuButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageMenuButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manageMenuButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(manageMenuButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 48, 280, 50));

        manageInfoButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageInfoButtonPanelMousePressed(evt);
            }
        });

        manageInfoButtonLabel.setForeground(new java.awt.Color(0, 0, 153));
        manageInfoButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageInfoButtonLabel.setText("Manage Info");

        javax.swing.GroupLayout manageInfoButtonPanelLayout = new javax.swing.GroupLayout(manageInfoButtonPanel);
        manageInfoButtonPanel.setLayout(manageInfoButtonPanelLayout);
        manageInfoButtonPanelLayout.setHorizontalGroup(
            manageInfoButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageInfoButtonPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(manageInfoButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        manageInfoButtonPanelLayout.setVerticalGroup(
            manageInfoButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageInfoButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(manageInfoButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 98, 280, 50));

        placeOrderRequestButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                placeOrderRequestButtonPanelMousePressed(evt);
            }
        });

        PlaceOrderButtonLabel.setForeground(new java.awt.Color(0, 0, 153));
        PlaceOrderButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PlaceOrderButtonLabel.setText("Place Order Request");

        javax.swing.GroupLayout placeOrderRequestButtonPanelLayout = new javax.swing.GroupLayout(placeOrderRequestButtonPanel);
        placeOrderRequestButtonPanel.setLayout(placeOrderRequestButtonPanelLayout);
        placeOrderRequestButtonPanelLayout.setHorizontalGroup(
            placeOrderRequestButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(placeOrderRequestButtonPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(PlaceOrderButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        placeOrderRequestButtonPanelLayout.setVerticalGroup(
            placeOrderRequestButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PlaceOrderButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(placeOrderRequestButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 280, 50));

        rightSystemAdminPanel.setPreferredSize(new java.awt.Dimension(940, 808));
        rightSystemAdminPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout systemAdminPanelLayout = new javax.swing.GroupLayout(systemAdminPanel);
        systemAdminPanel.setLayout(systemAdminPanelLayout);
        systemAdminPanelLayout.setHorizontalGroup(
            systemAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(systemAdminPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rightSystemAdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        systemAdminPanelLayout.setVerticalGroup(
            systemAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rightSystemAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        add(systemAdminPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void manageOrdersButtonLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageOrdersButtonLabelMousePressed
        manageOrders();
    }//GEN-LAST:event_manageOrdersButtonLabelMousePressed

    private void manageOrders() {
        // TODO add your handling code here:
        
        ManufacturerOrderDetailsJPanel manageOrderJPanel = new ManufacturerOrderDetailsJPanel(rightSystemAdminPanel,ecosystem,userAccount);
        rightSystemAdminPanel.add("ManageOrderJPanel",manageOrderJPanel);
        CardLayout layout = (CardLayout) rightSystemAdminPanel.getLayout();
        layout.next(rightSystemAdminPanel);
    }

    private void manageOrdersButtonPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageOrdersButtonPanelMousePressed
        // TODO add your handling code here:
        manageOrders();
    }//GEN-LAST:event_manageOrdersButtonPanelMousePressed

    private void manageMenuButtonLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageMenuButtonLabelMousePressed
        manageMenu();
    }//GEN-LAST:event_manageMenuButtonLabelMousePressed

    private void manageMenu() {
        // TODO add your handling code here:
      
        ManufacturerProductJPanel manageMenuJPanel = new ManufacturerProductJPanel(rightSystemAdminPanel,userAccount,ecosystem);
        rightSystemAdminPanel.add("ManageMenuJPanel",manageMenuJPanel);
        CardLayout layout = (CardLayout) rightSystemAdminPanel.getLayout();
        layout.next(rightSystemAdminPanel);
    }

    private void manageMenuButtonPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageMenuButtonPanelMousePressed
        // TODO add your handling code here:
        manageMenu();
    }//GEN-LAST:event_manageMenuButtonPanelMousePressed

    private void manageInfoButtonPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageInfoButtonPanelMousePressed
        manageInfo();
    }//GEN-LAST:event_manageInfoButtonPanelMousePressed

    private void placeOrderRequestButtonPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_placeOrderRequestButtonPanelMousePressed
        // TODO add your handling code here:
        
        PlaceOrderJPanel placeOrderJPanel = new PlaceOrderJPanel(rightSystemAdminPanel,userAccount,ecosystem,organization);
        rightSystemAdminPanel.add("PlaceOrderJPanel",placeOrderJPanel);
        CardLayout layout = (CardLayout) rightSystemAdminPanel.getLayout();
        layout.next(rightSystemAdminPanel);
    }//GEN-LAST:event_placeOrderRequestButtonPanelMousePressed

    private void manageInfo() {
        // TODO add your handling code here:
        
        ManufacturerDetailsJPanel manageRestaurantInformationJPanel = new ManufacturerDetailsJPanel(rightSystemAdminPanel,ecosystem, userAccount);
        rightSystemAdminPanel.add("ManageRestaurantInformationJPanel",manageRestaurantInformationJPanel);
        CardLayout layout = (CardLayout) rightSystemAdminPanel.getLayout();
        layout.next(rightSystemAdminPanel);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PlaceOrderButtonLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel manageInfoButtonLabel;
    private javax.swing.JPanel manageInfoButtonPanel;
    private javax.swing.JLabel manageMenuButtonLabel;
    private javax.swing.JPanel manageMenuButtonPanel;
    private javax.swing.JLabel manageOrdersButtonLabel;
    private javax.swing.JPanel manageOrdersButtonPanel;
    private javax.swing.JPanel placeOrderRequestButtonPanel;
    private javax.swing.JPanel rightSystemAdminPanel;
    private javax.swing.JPanel systemAdminPanel;
    // End of variables declaration//GEN-END:variables
}
