/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ThriftShopUnitWorkArea;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Helper.Email;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Role.CustomerRole;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.CustomerAccountActivationRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vishakha
 */
public class ThriftShopUnitWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VoluntaryOperatingUnitWorkRequestJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private Network network;
    private OrganizationDirectory organizationDirectory;
    public ThriftShopUnitWorkRequestJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.enterprise = enterprise;
     
        this.business = system;
        this.organizationDirectory = enterprise.getOrganizationDirectory();
        
        populateTable();
    }
    
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

        model.setRowCount(0);

        for (WorkRequest workRequest : business.getWorkQueue().getWorkRequestList()) {

            if (workRequest instanceof CustomerAccountActivationRequest) {
                Object[] row = new Object[model.getColumnCount()];
                row[0] = workRequest;
                row[1] = ((CustomerAccountActivationRequest) workRequest).getStatus();
                row[2] = ((CustomerAccountActivationRequest) workRequest).getUserName();
                row[3] = ((CustomerAccountActivationRequest) workRequest).getName();
                row[4] = ((CustomerAccountActivationRequest) workRequest).getUserEmailId();
                row[5] = ((CustomerAccountActivationRequest) workRequest).getArea();
                model.addRow(row);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        processJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1058, 840));
        setPreferredSize(new java.awt.Dimension(1058, 840));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestJTable.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        workRequestJTable.setForeground(new java.awt.Color(25, 56, 82));
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Request #", "Status", "UserName", "Name", "Email ID", "Area"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workRequestJTable.setSelectionBackground(new java.awt.Color(56, 90, 174));
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 854, 170));

        processJButton.setBackground(new java.awt.Color(255, 255, 255));
        processJButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        processJButton.setForeground(new java.awt.Color(25, 56, 82));
        processJButton.setText("Activate");
        processJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButtonActionPerformed(evt);
            }
        });
        add(processJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 56, 82));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE THRIFT SHOP USER REGISTRATION");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 41, 431, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void processJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButtonActionPerformed

         int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow >= 0) {
            CustomerAccountActivationRequest request = (CustomerAccountActivationRequest) workRequestJTable.getValueAt(selectedRow, 0);
            
                //Organization org = organizationDirectory.createOrganization(request.getOrgType(), request.getName(), request.getUserLocationPoint());
                Customer customer = new Customer();
                customer.setName(request.getName());
                customer.setUsername(request.getUserName());
                customer.setPassword(request.getUserPassword());
                customer.setEmailAddress(request.getUserEmailId());
                customer.setLatitude(request.getLatitude());
                customer.setLongitude(request.getLongitude());
                customer.setAddress(request.getArea());
                customer.setRole(new CustomerRole());
                Organization org = organizationDirectory.createOrganization(Organization.Type.Customer);
                business.getUserAccountDirectory().addUserAccount(customer);
                System.out.println("adding customer-->"+org.getCustomerDirectory().getCustomerList().size());
                Employee emp = org.getEmployeeDirectory().createEmployee(request.getName());
                UserAccount ua1 = org.getUserAccountDirectory().createUserAccount(request.getUserName(), request.getUserPassword(), emp, new CustomerRole());
                //CustomerDirectory customerDirectory= org.getCustomerDirectory().addCustomer(customer).;
     
               // org.getCustomerDirectory().addCustomer(customer);
            

            request.setStatus("Completed");
            JOptionPane.showMessageDialog(null, "Customer account has been activated successfully");
            populateTable();
            String subject = "Thrift Shop Customer Activation";
            String message = "Your customer account is activated with Thrift Shop. Now you can enjoy shopping, selling!!";
            Email.sendEmailMessage(request.getUserEmailId(), subject, message);
            
        } else {
            JOptionPane.showMessageDialog(null, "Please select a request message to process.");
            return;
        }
    }//GEN-LAST:event_processJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton processJButton;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
